# -*- coding: utf-8 -*-
"""Automation scheduling optimization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10-YDoI1BqbdQgcJQdW-0RHFPq467HL3E
"""

from pulp import *
import pandas as pd
import numpy as np
from itertools import product

# Example of data input (Synthetic Data)
list_employee = {
    "name": [ "Andi", "Budi", "Rizky", "Agus", "Eko", "Fajar", "Hendra", "Malik", "Teguh",
              "Bayu", "Rian", "Ilham", "Dimas", "Arif", "Wahyu", "Joko", "Galih", "Doni",
              "Taufik", "Yoga", "Reza", "Fikri", "Rama", "Eros", "Fauzi", "Imam", "Adi",
              "Siti", "Dewi", "Indah", "Utari", "Lina", "Ayu", "Mega", "Rina", "Melati",
              "Nina", "Wulan", "Putri", "Lestari","Viona","Kiko","Bonar","Hengki","Lita"],
    "gender" : ["Men","Men","Men","Men","Men","Men","Men","Men","Men",
                "Men","Men","Men","Men","Men","Men","Men","Men","Men",
                "Men","Men","Men","Men","Men","Men","Men","Men","Men",
                "Women","Women","Women","Women","Women","Women","Women","Women","Women",
                "Women","Women","Women","Women","Women","Men","Men","Men","Women"
                ]}

list_leave =  {
  "name": ["Malik", "Utari", "Kiko"],
  "day": ["Thursday","Saturday","Monday"],
  "week": ["Week 2","Week 3","Week 5"],
  "request_timeoff": ["On Leave","On Leave", "On Leave"]
}

convert_day = {
    "Monday": 0,
    "Tuesday": 1,
    "Wednesday": 2,
    "Thursday": 3,
    "Friday": 4,
    "Saturday": 5,
    "Sunday": 6
}

convert_week = {
    "Week 1": 0,
    "Week 2": 1,
    "Week 3": 2,
    "Week 4": 3,
    "Week 5": 4
}

class AutomationScheduling:
  def __init__(self, list1, list2, list3, list4):
    self.list_employee = list1
    self.list_leave = list2
    self.convert_day = list3
    self.convert_week = list4

  def DataPreparation(self):
    self.df_employee = pd.DataFrame(self.list_employee)
    self.leave_data = pd.DataFrame(self.list_leave)
    self.leave_data['day'] = self.leave_data['day'].map(self.convert_day)
    self.leave_data['week'] = self.leave_data['week'].map(self.convert_week)

  def Scheduling(self, day, week):
    i_e = self.df_employee['name'].tolist()
    d_e = list(range(0,day))
    w_e = list(range(0,week))

    leave_data = self.leave_data

    model = LpProblem("auto_scheduling", LpMinimize)

    x1 = LpVariable.dicts("x1", (i_e,d_e), 0, 1, cat='Binary')
    x2 = LpVariable.dicts("x2", (i_e,d_e), 0, 1, cat='Binary')
    x3 = LpVariable.dicts("x3", (i_e,d_e), 0, 1, cat='Binary')

    xd = LpVariable.dicts("xd", (i_e,d_e), 0, 1, cat='Binary')

    xw1 = LpVariable.dicts("xw1", (i_e,w_e), 0, 1, cat='Binary')
    xw2 = LpVariable.dicts("xw2", (i_e,w_e), 0, 1, cat='Binary')
    xw3 = LpVariable.dicts("xw3", (i_e,w_e), 0, 1, cat='Binary')

    #Optimization function
    model += lpSum([x1[i][d] + x2[i][d] + x3[i][d] for i,d in product(i_e,d_e)])

    # Create formulas to represent constraints:

    for w in w_e: # Capacity Weekday
      for d in range(0,5):
        model += lpSum([x1[i][w+d] for i in i_e]) >= 10
        model += lpSum([x2[i][w+d] for i in i_e]) >= 10
        model += lpSum([x3[i][w+d] for i in i_e]) >= 10

    for w in w_e: # Capacity Weekend
      for d in range(5,7):
        model += lpSum([x1[i][w+d] for i in i_e]) >= 9
        model += lpSum([x2[i][w+d] for i in i_e]) >= 8
        model += lpSum([x3[i][w+d] for i in i_e]) >= 8

    for i in i_e:
        for d in d_e:
            model += x1[i][d] + x2[i][d] + x3[i][d] <= 1*xd[i][d] #Only 1 Shift

    # Aggregate On Leave of each employee
    leave_count = (
    leave_data
    .groupby(['name', 'week'])
    .size()
    .to_dict()
                )

    for i in i_e:
      for w in list(range(5)): # 5 Weeks
        n_leave = leave_count.get((i, week), 0)
        if n_leave > 0:
          model += sum(x1[i][w+j] for j in range(7)) == (5 - n_leave) * xw1[i][week]
          model += sum(x2[i][w+j] for j in range(7)) == (5 - n_leave) * xw2[i][week]
          model += sum(x3[i][w+j] for j in range(7)) == (5 - n_leave) * xw3[i][week]

        else:
          model += sum(x1[i][w+j] for j in range(7)) == 5*xw1[i][week]
          model += sum(x2[i][w+j] for j in range(7)) == 5*xw2[i][week]
          model += sum(x3[i][w+j] for j in range(7)) == 5*xw3[i][week]

    for i in i_e:
      for w in w_e:
        model += xw1[i][w] + xw2[i][w] + xw3[i][w] == 1

    for i in i_e:
      for d in d_e:
        for e in range(len(leave_data['name'])):
          if i == leave_data['name'][e] and d == leave_data['day'][e]+(7*leave_data['week'][e]):
            model += x1[i][d] + x2[i][d] + x3[i][d] == 0


    for i in i_e:
      for w in w_e[:-1]:
        model += xw3[i][w]+xw1[i][w+1] <= 1

    for i in i_e:
      for w in w_e[:-1]:
        model += xw1[i][w]+xw1[i][w+1] <= 1
        model += xw2[i][w]+xw2[i][w+1] <= 1
        model += xw3[i][w]+xw3[i][w+1] <= 1

    for i in i_e:
      for d in d_e[:-6]:
          model += sum(xd[i][d+j] for j in range(6)) <= 5

    for i in i_e:
      for d in d_e[:-2]:
          model += xd[i][d] + xd[i][d+2] >= 1

    status=model.solve()
    checking=LpStatus[status]

    #store the results
    shifts = [s1, s2, s3]

    self.df = pd.DataFrame({
        k: v
        for idx, x in enumerate(shifts, start=1)
        for k, v in {
            f"shift_{idx}": [x[i][d].name for i,d in product(i_e,d_e)],
            f"val_shift_{idx}": [x[i][d].varValue for i,d in product(i_e,d_e)]
        }.items()
    })

  def CombineData(self):
    self.df['name'] = [self.df['shift_1'].str.split('_')[i][1] for i in range(len(self.df))]
    self.df['day'] = [int(self.df['shift_1'].str.split('_')[i][2]) for i in range(len(self.df))]
    self.leave_data['day_number'] = self.leave_data['day']+(7*self.leave_data['week'])

  def CreateSchedule(self):
    employee = self.df_employee
    working_shift = []

    scheduling = pd.merge(self.df, self.leave_data[['name','day_number','request_timeoff']], left_on=['name','day'], right_on=['name','day_number'], how='left')

    conditions = [
        (scheduling['request_timeoff'] == 'On Leave'),
        (scheduling['val_shift_1'] == 1),
        (scheduling['val_shift_2'] == 1),
        (scheduling['val_shift_3'] == 1),
    ]

    choices = [
        'On Leave',
        'Shift 1',
        'Shift 2',
        'Shift 3',
    ]

    scheduling['working_shift'] = np.select(conditions, choices, default='Day Off')

    scheduling['day'] = scheduling['day']+1
    scheduling = scheduling[['name','day','working_shift']]
    final_scheduling = pd.merge(scheduling, employee, how = 'left', on = 'name')
    final_scheduling = final_scheduling[['name','gender','day','working_shift']]
    return final_scheduling

  def run_all(self):
    self.DataPreparation()
    self.Scheduling(35, 5) # Generate 5 Weeks (35 Days)
    self.CombineData()
    self.CreateSchedule()

# Run the model
run_model = AutomationScheduling(list_employee, list_leave, convert_day, convert_week)
run_model.run_all()
final_scheduling = run_model.CreateSchedule()